AWSTemplateFormatVersion: "2010-09-09"
Description: SAM TypeScript Lambdas - Connect Async Job POC
Transform: AWS::Serverless-2016-10-31
  
Parameters:
  PrefixParameter:
    Type: String
    Description: "Naming standard prefix to use for resources"
    Default: "-modzel-"

  JobSubmissionLambdaName:
    Type: String
    Description: "Name of the job submission function, without PrefixParameter"
    Default: "connect-job-submission"

  LambdaProvisionedConcurrentExecutions:
    Type: String
    Description: "provisioned concurrency count for function"
    Default: "2"

  LambdaAlias:
    Type: String
    Description: "Alias $LATEST version of Lambda deployed. Needed for provisioning concurrency"
    Default: "live"

  ConnectInstanceId:
    Description: Connect Instance Id
    Type: String
    Default: ""

Conditions:
  ConnectInstanceIdDefined: !Not [!Equals ["", !Ref ConnectInstanceId]]

Globals:
  Function:
    Timeout: 8
    Runtime: nodejs12.x
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        LOG_LEVEL: debug
    
Resources:
  
  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "connect${PrefixParameter}job-queue"

  JobSubmissionFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "role${PrefixParameter}${JobSubmissionLambdaName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  JobSubmissionFunctionPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub "policy${PrefixParameter}${JobSubmissionLambdaName}"
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt JobQueue.Arn
      Roles:
        - !Ref JobSubmissionFunctionRole

  JobSubmissionFunction:
    Type: "AWS::Serverless::Function"
    DependsOn: JobSubmissionFunctionPolicy
    Properties:
      FunctionName: !Sub "lambda${PrefixParameter}${JobSubmissionLambdaName}"
      # Will publish a Version and create/update Alias `live` to point to it
      # An alias is needed so that we can use provisioned concurrency
      #AutoPublishAlias: !Ref LambdaAlias
      # ProvisionedConcurrencyConfig is only allowed here if AutoPublishAlias is set 
      #ProvisionedConcurrencyConfig:
      #  ProvisionedConcurrentExecutions: !Ref LambdaProvisionedConcurrentExecutions
      CodeUri: src/jobSubmission/
      Handler: handler.handler
      Role: !GetAtt JobSubmissionFunctionRole.Arn
      Environment:
        Variables:
          QUEUE_URL: !Ref JobQueue

  # allow connect to invoke the function by its alias
  # JobSubmissionFunctionConnectPermissionOnAlias:
  #   Condition: ConnectInstanceIdDefined
  #   Type: AWS::Lambda::Permission
  #   # hack, depends on generated resource name. Can't use !Sub
  #   DependsOn: "JobSubmissionFunctionAliaslive"
  #   Properties:
  #     FunctionName: !Join
  #       - ":"
  #       - - !GetAtt JobSubmissionFunction.Arn
  #         - !Ref LambdaAlias
  #     Action: "lambda:InvokeFunction"
  #     Principal: connect.amazonaws.com
  #     SourceAccount:
  #       Ref: "AWS::AccountId"
  #     SourceArn: !Sub "arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}"

  JobProcessFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "role${PrefixParameter}JobProcess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  JobProcessFunctionPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub "policy${PrefixParameter}JobProcess"
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt JobQueue.Arn
      Roles:
        - !Ref JobProcessFunctionRole

  JobProcessFunction:
    Type: "AWS::Serverless::Function"
    DependsOn: JobProcessFunctionPolicy
    Properties:
      FunctionName: !Sub "lambda${PrefixParameter}JobProcess"
      CodeUri: src/jobProcess/
      Handler: handler.handler
      Role: !GetAtt JobProcessFunctionRole.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt JobQueue.Arn
            BatchSize: 10
            Enabled: true

Outputs:
  JobQueue:
    Description: "Job Queue name"
    Value: !Ref JobQueue
  JobSubmissionFunction:
    Description: "Job Submission function name"
    Value: !Ref JobSubmissionFunction
  JobProcessFunction:
    Description: "Job Process function name"
    Value: !Ref JobProcessFunction
    